# Generated by Django 5.2.7 on 2025-10-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport_type', models.CharField(choices=[('tennis', 'Tennis'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('paddle', 'Paddle'), ('futsal', 'Futsal'), ('table_tennis', 'Table Tennis')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Court/')),
                ('facilities', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(help_text='Format: 628123456789 (without +)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='Auth_Profile.user')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Court.court')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('court', 'date', 'start_time')},
            },
        ),
    ]
