# Generated by Django 5.2.8 on 2025-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image',
        ),
        migrations.AddField(
            model_name='court',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
