# Generated by Django 5.2.7 on 2025-10-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Profile', '0001_initial'),
        ('Court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='Auth_Profile.user'),
        ),
    ]
