# Generated by Django 5.2.6 on 2025-10-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0002_court_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='owner_phone',
            field=models.CharField(help_text='Format: 628123456789 (without +)', max_length=20),
        ),
    ]
