# Generated by Django 5.2.7 on 2025-10-22 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='coach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
