# Generated by Django 5.2.7 on 2025-10-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_rename_name_coach_title_coach_created_at_coach_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coach/'),
        ),
    ]
