# Generated by Django 5.2.7 on 2025-10-23 07:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_alter_coach_options_alter_coach_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['category', 'price'], name='Coach_coach_categor_2949e0_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['created_at'], name='Coach_coach_created_87cb92_idx'),
        ),
    ]
