# Generated by Django 5.2.7 on 2025-10-23 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0004_alter_coach_price_alter_coach_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
