# Generated by Django 5.2.7 on 2025-10-23 14:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0005_coach_address_coach_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['location'], name='Coach_coach_locatio_d19cab_idx'),
        ),
    ]
