# Generated by Django 5.2.7 on 2025-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0007_coach_endtime_coach_peserta_coach_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
