# Generated by Django 5.2.7 on 2025-10-24 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0008_coach_instagram_link_coach_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='mapsLink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
