# Generated by Django 5.2.7 on 2025-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0009_coach_mapslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='location',
            field=models.CharField(max_length=400),
        ),
    ]
