# Generated by Django 5.2.7 on 2025-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0010_alter_coach_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='mapsLink',
            field=models.URLField(max_length=400),
        ),
    ]
