# Generated by Django 5.2.7 on 2025-10-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Profile', '0001_initial'),
        ('Coach', '0011_alter_coach_mapslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='peserta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Auth_Profile.user'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='Auth_Profile.user'),
        ),
    ]
