# Generated by Django 5.2.6 on 2025-10-08 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tennis', 'Tennis'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('paddle', 'Paddle'), ('futsal', 'Futsal'), ('table_tennis', 'Table Tennis'), ('jogging', 'Jogging')], default='sepakbola')),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('total_participants', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
