# Generated by Django 5.2.7 on 2025-10-24 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tennis', 'Tennis'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('paddle', 'Paddle'), ('futsal', 'Futsal'), ('table_tennis', 'Table Tennis'), ('jogging', 'Jogging')], default='soccer', max_length=20)),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('lokasi', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth_Profile.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostParticipants',
            fields=[
                ('pk_participant', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_Profile.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport_Partner.partnerpost')),
            ],
            options={
                'unique_together': {('post_id', 'participant')},
            },
        ),
    ]
