# Generated by Django 5.2.6 on 2025-10-22 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_Partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpost',
            name='time',
        ),
        migrations.AddField(
            model_name='partnerpost',
            name='jam_mulai',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partnerpost',
            name='jam_selesai',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partnerpost',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
