# Generated by Django 5.2.6 on 2025-10-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_Partner', '0002_remove_partnerpost_time_partnerpost_jam_mulai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerpost',
            old_name='location',
            new_name='lokasi',
        ),
    ]
