# Generated by Django 5.2.6 on 2025-10-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Profile', '0001_initial'),
        ('Sport_Partner', '0003_rename_location_partnerpost_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpost',
            name='total_participants',
        ),
        migrations.AddField(
            model_name='partnerpost',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth_Profile.user'),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='category',
            field=models.CharField(choices=[('tennis', 'Tennis'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('paddle', 'Paddle'), ('futsal', 'Futsal'), ('table_tennis', 'Table Tennis'), ('jogging', 'Jogging')], default='soccer', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='jam_mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='jam_selesai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='partnerpost',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PostParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_Profile.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport_Partner.partnerpost')),
            ],
            options={
                'unique_together': {('post_id', 'participant')},
            },
        ),
    ]
