# Generated by Django 5.2.6 on 2025-10-24 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_Partner', '0004_remove_partnerpost_total_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postparticipants',
            name='id',
        ),
        migrations.AddField(
            model_name='postparticipants',
            name='pk_participant',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
