# Generated by Django 5.2.7 on 2025-10-23 12:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Pendaftaran Event', 'verbose_name_plural': 'Pendaftaran Event'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Jakarta', max_length=100, verbose_name='Kota'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Durasi (jam)'),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Instagram'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('newbie', 'Newbie'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='beginner', max_length=50, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.TextField(default='Unknown Address', verbose_name='Alamat Lengkap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='Unknown Place', max_length=200, verbose_name='Nama Tempat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='min_participants',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimal Peserta'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Untitled Event', max_length=200, verbose_name='Nama Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='payment_info',
            field=models.TextField(blank=True, null=True, verbose_name='Info Pembayaran'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Harga per Orang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='refund_policy',
            field=models.CharField(choices=[('no_refund', 'Tidak Ada Refund'), ('partial', 'Refund Sebagian'), ('full', 'Refund Penuh')], default='no_refund', max_length=50, verbose_name='Kebijakan Refund'),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, help_text='Perlengkapan yang dibutuhkan, aturan, dll', null=True, verbose_name='Persyaratan'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pembayaran'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Bukti Pembayaran'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_verified',
            field=models.BooleanField(default=False, verbose_name='Pembayaran Terverifikasi'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 23, 12, 5, 36, 406595, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Daftar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tennis', 'Tennis'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('paddle', 'Paddle'), ('futsal', 'Futsal'), ('table_tennis', 'Table Tennis'), ('swimming', 'Swimming')], default='badminton', max_length=50, verbose_name='Kategori Olahraga'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Tanggal Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maksimal Peserta'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Waktu Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Event.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='Nama Tampilan')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='organizers/')),
                ('is_superhost', models.BooleanField(default=False, verbose_name='Badge Superhost')),
                ('total_events', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='Event.eventorganizer', verbose_name='Penyelenggara'),
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Event.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Event',
                'verbose_name_plural': 'Review Event',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
