# Generated by Django 5.2.7 on 2025-10-23 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Profile', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWN', 'OWNER'), ('B', 'BIASA'), ('C', 'COACH')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
