# Generated by Django 5.2.7 on 2025-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Profile', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('BIASA', 'BIASA'), ('COACH', 'COACH')]),
        ),
    ]
